from .random_triplet import RandomTriplet
from .random_triplet_min_margin import RandomMinimumTriplet
from .triplet_local import LocalTriplet
from .random_triplet_precompute import RandomTripletPreselected
from .multi_triplet_pre import MultiTripletPreselected